steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/adept-student-347908/nodejs:latest', '.']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/adept-student-347908/nodejs:latest']
 
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'nodejs', '--image', 'gcr.io/adept-student-347908/nodejs', '--port', '8080', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']
images:
 - 'gcr.io/adept-student-347908/nodejs:latest'
